use std::env;
use std::path::PathBuf;

pub const SSHD_DROPIN_PATH: &str = "/etc/ssh/sshd_config.d/99-shhup.conf";

pub const HARDENED_SSHD_CONFIG: &str = r#"# Managed by shhup.
# Keeps SSH key-based and avoids granting root access over SSH.
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitRootLogin no
MaxAuthTries 3
X11Forwarding no
AllowTcpForwarding no
ClientAliveInterval 300
ClientAliveCountMax 2
"#;

pub fn default_key_path() -> PathBuf {
    home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".ssh")
        .join("id_ed25519_shhup")
}

pub fn default_key_comment() -> String {
    let user = env::var("USER").unwrap_or_else(|_| "user".to_string());
    let host = env::var("HOSTNAME").unwrap_or_else(|_| "host".to_string());
    format!("{user}@{host} generated by shhup")
}

pub fn home_dir() -> Option<PathBuf> {
    env::var_os("HOME").map(PathBuf::from)
}

pub fn validate_username(username: &str) -> Result<(), String> {
    if username.is_empty() {
        return Err("username is required".to_string());
    }

    if username == "root" {
        return Err("shhup will not create or configure root access".to_string());
    }

    if username.len() > 32 {
        return Err("username must be 32 characters or fewer".to_string());
    }

    let mut chars = username.chars();
    let first = chars.next().expect("checked non-empty username");
    if !(first.is_ascii_lowercase() || first == '_') {
        return Err("username must start with a lowercase letter or underscore".to_string());
    }

    if !chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-') {
        return Err(
            "username may only contain lowercase letters, digits, underscores, and hyphens"
                .to_string(),
        );
    }

    Ok(())
}

pub fn connection_hint(username: &str, host: &str, key_path: &str) -> String {
    format!("ssh -i {key_path} {username}@{host}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn root_user_is_rejected() {
        assert!(validate_username("root").is_err());
    }

    #[test]
    fn normal_linux_usernames_are_accepted() {
        assert!(validate_username("deploy").is_ok());
        assert!(validate_username("app_user-1").is_ok());
    }

    #[test]
    fn uppercase_and_empty_usernames_are_rejected() {
        assert!(validate_username("").is_err());
        assert!(validate_username("Deploy").is_err());
    }

    #[test]
    fn hardened_config_disables_root_and_password_auth() {
        assert!(HARDENED_SSHD_CONFIG.contains("PermitRootLogin no"));
        assert!(HARDENED_SSHD_CONFIG.contains("PasswordAuthentication no"));
        assert!(HARDENED_SSHD_CONFIG.contains("PubkeyAuthentication yes"));
    }

    #[test]
    fn connection_hint_uses_key_user_and_host() {
        assert_eq!(
            connection_hint("deploy", "server.example", "~/.ssh/id_ed25519"),
            "ssh -i ~/.ssh/id_ed25519 deploy@server.example"
        );
    }
}
